#!/bin/bash
# Modified and Deployed by Bjorn SSH and OpenVPN

#Requirement
if [ ! -e /usr/bin/curl ]; then
   yum -y update && yum -y upgrade
   yum -y install curl
fi

# initializing var
OS=`uname -m`;
open_ip=$(curl -4 icanhazip.com)
if [ $open_ip = "" ]; then
   open_ip=`ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1`;
fi
server_ip="s/xxxxxxxxx/$open_ip/g";

# go to root
cd

# setting repo
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
rpm -Uvh epel-release-latest-7.noarch.rpm
rpm -Uvh remi-release-7.rpm
wget http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
rpm -Uvh rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
sed -i 's/enabled = 1/enabled = 0/g' /etc/yum.repos.d/rpmforge.repo
sed -i -e "/^\[remi\]/,/^\[.*\]/ s|^\(enabled[ \t]*=[ \t]*0\\)|enabled=1|" /etc/yum.repos.d/remi.repo
rm -f *.rpm

# set time GMT +8
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# disable se linux
echo 0 > /selinux/enforce
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service sshd restart

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.d/rc.local

#Add DNS Server ipv4
echo "nameserver 1.1.1.1" > /etc/resolv.conf
echo "nameserver 1.0.0.1" >> /etc/resolv.conf
sed -i '$ i\echo "nameserver 1.1.1.1" > /etc/resolv.conf' /etc/rc.local
sed -i '$ i\echo "nameserver 1.0.0.1" >> /etc/resolv.conf' /etc/rc.local
sed -i '$ i\echo "nameserver 1.1.1.1" > /etc/resolv.conf' /etc/rc.d/rc.local
sed -i '$ i\echo "nameserver 1.0.0.1" >> /etc/resolv.conf' /etc/rc.d/rc.local

# install wget and curl
yum -y install nano wget curl
yum -y install firewalld
systemctl start firewalld
systemctl enable firewalld

# install fail2ban
yum -y install fail2ban
service fail2ban restart
chkconfig fail2ban on

# install dropbear
yum -y install dropbear
echo "OPTIONS=\"-p 109 -p 110 -p 442\"" > /etc/sysconfig/dropbear
echo "/bin/false" >> /etc/shells
firewall-cmd --zone=public --add-port=109/tcp --permanent
firewall-cmd --zone=public --add-port=110/tcp --permanent
firewall-cmd --zone=public --add-port=442/tcp --permanent
firewall-cmd --reload
service dropbear restart
chkconfig dropbear on

# setting port ssh
sed -i 's/#Port 22/Port 22/g' /etc/ssh/sshd_config
service sshd restart
chkconfig sshd on

# install ddos deflate
cd
wget http://www6.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/grepcidr-2.0-1.el7.art.x86_64.rpm
rpm -Uvh grepcidr-2.0-1.el7.art.x86_64.rpm
yum install grepcidr
yum -y install dnsutils bind-utils dsniff unzip net-snmp net-snmp-utils tcpdump
wget https://github.com/jgmdev/ddos-deflate/archive/master.zip
unzip master.zip
cd ddos-deflate-master
./install.sh
rm -rf /root/master.zip
cd

# setting banner
rm /etc/issue.net -f
wget -O /etc/issue.net "https://www.dropbox.com/s/7p3a7h8fglsd3sj/issue.net?dl=1"
sed -i '/Banner/a Banner="/etc/issue.net"' /etc/ssh/sshd_config
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
service sshd restart
service dropbear restart

# install badvpn
wget -O /usr/bin/badvpn-udpgw "https://raw.githubusercontent.com/shigeno143/OCSPanelCentos6/master/badvpn-udpgw64"
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.d/rc.local
chmod +x /usr/bin/badvpn-udpgw
yum install screen -y
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300
firewall-cmd --zone=public --add-port=7300/tcp --permanent
firewall-cmd --reload


# install openvpn
yum -y install openvpn
wget -O /tmp/easyrsa https://github.com/OpenVPN/easy-rsa-old/archive/2.3.3.tar.gz
tar xfz /tmp/easyrsa
mkdir /etc/openvpn/easy-rsa
cp -rf easy-rsa-old-2.3.3/easy-rsa/2.0/* /etc/openvpn/easy-rsa
mkdir /etc/openvpn/easy-rsa/keys
sed -i 's/export PKCS11/#export PKCS11/g' /etc/openvpn/easy-rsa/vars
sed -i 's/export KEY_CN/#export KEY_CN/g' /etc/openvpn/easy-rsa/vars
sed -i 's/export KEY_EMAIL=mail@host.domain/#export KEY_EMAIL=mail@host.domain/g' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_COUNTRY="US"|export KEY_COUNTRY="PH"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_PROVINCE="CA"|export KEY_PROVINCE="Talisay"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_CITY="SanFrancisco"|export KEY_CITY="Cebu"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_ORG="Fort-Funston"|export KEY_ORG="Bjorn"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_EMAIL="me@myhost.mydomain"|export KEY_EMAIL="binarykorra@icloud.com"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_NAME=changeme|export KEY_NAME="server"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_OU=changeme|export KEY_OU="BjornVPN"|' /etc/openvpn/easy-rsa/vars
#Create Diffie-Helman Pem
openssl dhparam -out /etc/openvpn/dh2048.pem 2048
# Create PKI
cd /etc/openvpn/easy-rsa
cp openssl-1.0.0.cnf openssl.cnf
. ./vars
./clean-all
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --initca $*
# create key server
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --server server
# setting KEY CN
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" client
cd
cd /etc/openvpn/easy-rsa/keys
cp ca.crt server.crt server.key /etc/openvpn
cd
# setting server
cat > /etc/openvpn/server.conf <<-END
port 465
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key 
dh dh2048.pem
client-cert-not-required
username-as-common-name
plugin /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so login
server 192.168.100.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
push "route-method exe"
push "route-delay 2"
duplicate-cn
push "route-method exe"
push "route-delay 2"
keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
log openvpn.log
verb 3
cipher AES-256-CBC
END

cd

# create openvpn config
cat > openvpn.ovpn <<-END
#OpenVPN and SSH Panel by Bjorn VPN

client
dev tun
proto tcp
remote xxxxxxxxx 465
persist-key
persist-tun
dev tun
pull
resolv-retry infinite
nobind
remote-cert-tls server
verb 5
mute 2
mute-replay-warnings
auth-user-pass
setenv opt block-outside-dns
redirect-gateway def1
script-security 2
route 0.0.0.0 0.0.0.0
route-method exe
route-delay 2
cipher AES-256-CBC
setenv CLIENT_CERT 0
dhcp-option DOMAIN 1dot1dot1dot1.cloudflare-dns.com

http-proxy xxxxxxxxx 8000
http-proxy-option CUSTOM-HEADER ""
http-proxy-option CUSTOM-HEADER "PUT https://s3.amazonaws.com HTTP/1.0"
http-proxy-option CUSTOM-HEADER "Host: s3.amazonaws.com"
http-proxy-option CUSTOM-HEADER "Proxy-Connection: Keep-Alive"
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
keepalive 2 60
verb 5

END
echo '<ca>' >> openvpn.ovpn
cat /etc/openvpn/ca.crt >> openvpn.ovpn
echo '</ca>' >> openvpn.ovpn
sed -i $server_ip openvpn.ovpn;

#setup firewall
firewall-cmd --get-active-zones
firewall-cmd --zone=trusted --add-service openvpn
firewall-cmd --zone=trusted --add-service openvpn --permanent
firewall-cmd --list-services --zone=trusted
firewall-cmd --add-masquerade
firewall-cmd --permanent --add-masquerade
firewall-cmd --query-masquerade
SHARK=$(ip route get 1.1.1.1 | awk 'NR==1 {print $(NF-2)}')
firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A POSTROUTING -s 192.168.100.0/24 -o $SHARK -j MASQUERADE
firewall-cmd --zone=public --add-port=465/tcp --permanent
firewall-cmd --reload
#forward ipv4
sysctl -w net.ipv4.ip_forward=1
touch /usr/lib/sysctl.d/sysctl.conf
cat > /usr/lib/sysctl.d/sysctl.conf <<-END
net.ipv4.ip_forward = 1
END
systemctl restart network.service
systemctl -f enable openvpn@server.service
systemctl start openvpn@server.service
systemctl status openvpn@server.service
chkconfig openvpn on


##################squid3.1.23
cd

#dependencies
yum install -y binutils gcc-c++
yum install -y perl gcc autoconf automake make sudo wget
yum install -y libxml2-devel libcap-devel
yum install -y libtool-ltdl-devel
 
# install squid
yum -y install squid
wget -O /etc/squid/squid.conf "https://raw.githubusercontent.com/Urabephc/Autoscript/master/Centos7/squid-centos7.conf"
sed -i $MYIP2 /etc/squid/squid.conf;
systemctl restart squid
systemctl enable squid


 
# add firewall rule to allow inbound port connections
firewall-cmd --zone=public --add-port=80/tcp --permanent
firewall-cmd --zone=public --add-port=3128/tcp --permanent
firewall-cmd --zone=public --add-port=8000/tcp --permanent
firewall-cmd --zone=public --add-port=8080/tcp --permanent
firewall-cmd --zone=public --add-port=8888/tcp --permanent
firewall-cmd --reload
 

cd
touch /root/log.txt
cat > /root/log.txt <<-END
"---------------------------Squid Commands---------------------------"
"           to start:    # /usr/sbin/squid                           "
"            to stop:    # /usr/sbin/squid -k shutdown               "
"          to reload:    # /usr/sbin/squid -k reconfigure            "
" to test if running:    # ps uax|grep squid                         "
"      to check logs:    # tail /var/logs/cache.log                  "
"--------------------------------------------------------------------"
"-------------------------OpenVPN Commands---------------------------"
"           to start:    # systemctl start openvpn@server.service    "
"            to stop:    # systemctl stop openvpn@server.service     "
"          to reload:    # systemctl restart openvpn@server.service  "
"    to check status:    # systemctl status openvpn@server.service   "
"--------------------------------------------------------------------"
"----------------------     Add Users     ---------------------------"
"             to add:    # useradd enterusernamehere                 "
"      change passwd:    # echo "username:password" | chpasswd       "
"          to remove:    # userdel username                          "
"--------------------------------------------------------------------"
Application & Port Information
   - OpenVPN     : TCP 465 
   - OpenSSH     : 22, 143, 90
   - Dropbear    : 109, 110, 442
   - Squid Proxy : 80, 8000, 8080, 8888, 3128 (limit to IP Server)
   - Badvpn      : 7300
Script Compiled By Tacome9 (https://www.phcorner.net/members/228541/)
END

#clearing history
history -c

# info
clear

echo " "
echo "INSTALLATION COMPLETE!"
echo " "
echo "---------------------------Squid Commands---------------------------"
echo "           to start:    # /usr/sbin/squid                           "
echo "            to stop:    # /usr/sbin/squid -k shutdown               "
echo "          to reload:    # /usr/sbin/squid -k reconfigure            "
echo " to test if running:    # ps uax|grep squid                         "
echo "      to check logs:    # tail /var/logs/cache.log                  "
echo "--------------------------------------------------------------------"
echo "-------------------------OpenVPN Commands---------------------------"
echo "           to start:    # systemctl start openvpn@server.service    "
echo "            to stop:    # systemctl stop openvpn@server.service     "
echo "          to reload:    # systemctl restart openvpn@server.service  "
echo "    to check status:    # systemctl status openvpn@server.service   "
echo "--------------------------------------------------------------------"
echo "----------------------     Add Users     ---------------------------"
echo "             to add:    # useradd enterusernamehere                 "
echo "      change passwd:    # echo "username:password" | chpasswd       "
echo "          to remove:    # userdel username                          "
echo "--------------------------------------------------------------------"
echo "Application & Port Information"
echo "   - OpenVPN     : TCP 465 "
echo "   - OpenSSH     : 22, 143, 90"
echo "   - Dropbear    : 109, 110, 442"
echo "   - Squid Proxy : 80, 8000, 8080, 8888, 3128 (limit to IP Server)" 
echo "   - Badvpn      : 7300"
echo " "
echo "----- Script Created By Steven Indarto(fb.com/stevenindarto2) ------"
echo " Created by Hosting Termurah, Modified by Tacome9 and Deployed by Bjorn VPN - (https://www.phcorner.net/members/228541/)"
